# Generated by Django 4.0.5 on 2022-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_slug_alter_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='books/picture'),
        ),
    ]
