# Generated by Django 4.0.5 on 2022-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
