# Generated by Django 4.0.5 on 2022-07-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Sold', 'Sold'), ('Rented', 'Rented')], max_length=50),
        ),
    ]
